version: '3.1'

services:
  api:
    build: .
    container_name: parking-api
    ports:
      - 8000:8000
    environment:
      PORT: 8000
    volumes:
      - .:/usr/src/app

  mongo:
    container_name: mongodb
    image: mongo
    restart: unless-stopped
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
